export const SEARCH_KEYWORD_REQUEST = 'SEARCH_KEYWORD_REQUEST';
export const SEARCH_KEYWORD_SUCCESS = 'SEARCH_KEYWORD_SUCCESS';
export const SEARCH_KEYWORD_FAIL = 'SEARCH_KEYWORD_FAIL';

export const SEARCH_CATEGORY_REQUEST = 'SEARCH_CATEGORY_REQUEST';
export const SEARCH_CATEGORY_SUCCESS = 'SEARCH_CATEGORY_SUCCESS';
export const SEARCH_CATEGORY_FAIL = 'SEARCH_CATEGORY_FAIL';
