export const SEARCH_KEYWORD_REQUEST = 'SEARCH_KEYWORD_REQUEST';
export const SEARCH_KEYWORD_SUCCESS = 'SEARCH_KEYWORD_SUCCESS';
export const SEARCH_KEYWORD_FAIL = 'SEARCH_KEYWORD_FAIL';

export const SEARCH_CATEGORY_REQUEST = 'SEARCH_CATEGORY_REQUEST';
export const SEARCH_CATEGORY_SUCCESS = 'SEARCH_CATEGORY_SUCCESS';
export const SEARCH_CATEGORY_FAIL = 'SEARCH_CATEGORY_FAIL';


export const PRODUCTS_RECOMMEND_REQUEST = 'PRODUCTS_RECOMMEND_REQUEST';
export const PRODUCTS_RECOMMEND_SUCCESS = 'PRODUCTS_RECOOMEND_SUCCESS';
export const PRODUCTS_RECOMMEND_FAIL = 'PRODUCTS_RECOMMEND_FAIL';
