const data = {
    products: [
      {
        _id: '1',
        name: 'Converse',
        category: 'Shoes',
        image: "..//../image/Product/Converse/162053c-7.jpg",
        price: 120,
        countInStock: 10,
        brand: 'Converse',
        description: 'Giày Converse Chuck Taylor All Star Wordmark 2.0 với nền trắng basic cùng logo Converse màu xanh in ngang dọc thân giày tạo điểm nhấn cho sản phẩm. Đây là một mẫu giày thời trang tinh tế, đơn giản và phù hợp với nhiều sự kiện.',
      },
      {
        _id: '2',
        name: 'Converse',
        category: 'Shoes',
        image: "..//../image/Product/Converse/165958c-9.jpg",
        price: 120,
        countInStock: 10,
        brand: 'Converse',
        description: 'Giay dep',
      },
      {
        _id: '3',
        name: 'Converse',
        category: 'Shoes',
        image: "..//../image/Product/Converse/165958c-9.jpg",
        price: 120,
        countInStock: 10,
        brand: 'Converse',
        description: 'Converse CX sở hữu những cải tiến đáng giá nhất của hãng từ chất liệu làm nên sản phẩm cho đến bộ đế đầy tính sáng tạo và đột phá, làm nên đặc trưng không thể trộn lẫn: tấm vải nền mang tên CX, một loại vải tổng hợp vừa dẻo dai nhưng vẫn tạo ra sự ôm sát vừa vặn với chân người dùng đặc biệt là vẫn giữ được vẻ ngoài đầy tính truyền thống của Converse. Tiếp theo là hệ thống đệm bọt CX là kết hợp giữa đế PU và đế Phylon được xếp chồng lên nhau mang lại sự êm ái khi di chuyển',
      },
      {
        _id: '4',
        name: 'Converse',
        category: 'Shoes',
        image: "..//../image/Product/Converse/165958c-9.jpg",
        price: 120,
        countInStock: 10,
        brand: 'Converse',
        description: 'Giay dep',
      },
      {
        _id: '5',
        name: 'Converse',
        category: 'Shoes',
        image: "..//../image/Product/Converse/165958c-9.jpg",
        price: 120,
        countInStock: 0,
        brand: 'Converse',
        description: 'Giay dep',
      },
      {
        _id: '6',
        name: 'Converse',
        category: 'Shoes',
        image: "..//../image/Product/Converse/165958c-9.jpg",
        price: 120,
        countInStock: 10,
        brand: 'Converse',
        description: 'Giay dep',
      },
    ],
};

module.exports = data;